spring:
  application:
    name: "@project.artifactId@"
  datasource:
    url: jdbc:sqlite://D:/sqlite.db
    driver-class-name: org.sqlite.JDBC

server:
  port: 39698
  servlet:
    context-path: /verification
  tomcat:
    use-relative-redirects: true